//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPM_IPS.JDCCCAJDOMDCMProyectoIPS
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "JDCCCAJDOMDCM_DSLProyectoIPS";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"JDCCCAJDOMDCMProyectoIPS";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"UPM_IPS";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.0.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID JDCCCAJDOMDCMProyectoIPSDiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(JDCCCAJDOMDCMProyectoIPSCommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID JDCCCAJDOMDCMProyectoIPSExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(JDCCCAJDOMDCMProyectoIPSCommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewJDCCCAJDOMDCMProyectoIPSExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(JDCCCAJDOMDCMProyectoIPSCommandSetId), 0x0001);
	
		// Package identifier
		public const string JDCCCAJDOMDCMProyectoIPSPackageId = "be39daec-fbd1-404b-9f14-75443666ee53";
		
		// Editor factory identifier
		public const string JDCCCAJDOMDCMProyectoIPSEditorFactoryId = "0cae6051-815c-4693-9fb8-e2d973ea5c4c";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string JDCCCAJDOMDCMProyectoIPSModelExplorerToolWindowId = "3be62c41-289f-473f-abfd-83a23ae7577f";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace UPM_IPS.JDCCCAJDOMDCMProyectoIPS
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string JDCCCAJDOMDCMProyectoIPSCommandSetId = "b8dc80cc-3428-4bc6-83c3-e34483c1b546";
	}
}